plugins {
    id 'java'
}

allprojects {

    group = 'com.prasad'
    version = '1.0.0'

    repositories {
        mavenCentral()
    }
}

subprojects {

    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    dependencies {

        testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    }

    test {
        useJUnitPlatform()
    }
}

allprojects {
    repositories {
        mavenCentral()
        maven {
            url "https://packages.confluent.io/maven/"
        }
    }
}

tasks.register("runAllServices") {
    dependsOn(
            ":news-producer-service:bootRun",
            ":ai-analysis-service:bootRun"
    )
}